In [2]:
import numpy as np

In [14]:
# list of numbers
x = [2, 3, 4, 5, 6, 7, 8]

# to create a numpy array
y = np.array(x)
# or
a = np.array([2, 3, 4, 5, 6, 7, 8])
a.dtype

dtype('int32')

In [15]:
# to get the dimension of an array
a.ndim

1

In [16]:
# to check the shape
a.shape

(7,)

In [17]:
# check the size/total size consumed by an array in bytes
a.nbytes

28

In [18]:
# to check the size of an array
a.size

7

In [21]:
# to create a matrix
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# to create a tensor
ten = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [1, 2, 3]]])
ten


array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [25]:
# Different ways of creating Numpy Arrays
# array method
nums = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# arange method
arange = np.arange(2,9)
arange
# or
arn = np.arange(2, 9, 2)
arn

array([2, 4, 6, 8])

In [36]:
# zeros method
zer = np.zeros([2,4])
zer

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
# ones mehod
one = np.ones([3, 3])
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# eye/identity method
identity = np.identity(4)
print(identity)
print('------------------------')
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:
# linspace method
lin = np.linspace(2, 10, 5)
lin

array([ 2.,  4.,  6.,  8., 10.])

In [55]:
# random method
print('Random Numbers')
ran = np.random.rand(4, 2)
print(ran)

print('----------------------------------------------------------')
print('Normal/Gaussian Distribution')
# random numbers with the gaussian/normal distribuion
rnd = np.random.randn(3, 3)
print(rnd)

print('-----------------------------------------------------------')
print('Random Integers')
# random integers
rand = np.random.randint(20, 100, 5)
print(rand)

Random Numbers
[[0.81668496 0.83184785]
 [0.63819284 0.44758706]
 [0.04453418 0.63905233]
 [0.01233756 0.37699878]]
----------------------------------------------------------
Normal/Gaussian Distribution
[[-1.9821486  -0.50721372 -0.324175  ]
 [-0.88624478 -0.20045942 -1.87460964]
 [ 0.76159188 -1.24260233  0.37641876]]
-----------------------------------------------------------
Random Integers
[74 58 23 72 79]


In [57]:
# reshaping numpy arrays
n = np.random.randint(10, 100, 15).reshape(5, 3)
n

array([[39, 70, 50],
       [40, 89, 64],
       [28, 47, 85],
       [21, 43, 62],
       [55, 27, 98]])

In [69]:
# STATISTICS
# creating random five integers
d = np.random.randint(10, 100, 5)
print(d)

# finding min and max values
dmin = d.min()
print(dmin)

dmax = d.max()
print(dmax)

# index of max and min value
print(d.argmax())
print(d.argmin())

# mean
print(d.mean())

# median
print(np.median(d))

# standard deviation
print(d.std())

# variance
print(np.var(d))

[43 98 46 39 35]
35
98
1
4
52.2
43.0
23.198275797998438
538.1600000000001


In [81]:
# array indexing
# 1D
y = np.arange(10)
print(y)
print(y[2:5])

# 2D
x = np.linspace(1, 24, 6).reshape(2, 3)
x
print(x[:2, :2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[[ 1.   5.6]
 [14.8 19.4]]


In [4]:
# Maths with numpy
nums = np.arange(1, 16)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
# adding two arrays
nums2 = nums +nums
nums2
# adding a number to an array
nums3 = nums + 2
nums3
# subtraction
nums4 = nums-9
nums4
# multiplication
nums5 = nums *2
nums5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [6]:
# log
np.log(nums)
# square
np.square(nums)
# squareroot
np.sqrt(nums)
# floor-the largest integer greater than or equalto each element
np.floor(nums/2)
# ceiling-the smallest integer greater than or equalto each element
np.ceil(nums/2)
# exponential function
x = np.exp(nums)
# sine function
x = np.sin(nums)
# cosine function
x = np.cos(nums)

In [9]:
# LINEAR ALGEBRA OPERATIONS WITH NUMPY ARRAY
# Finding the vector dot product
# create two vectors
x = np.array([2, 5])
y = np.array([6, 4]) #the dot product of the two vectors is (2*6)+(5*4)=32

# to find the dot product without using the numpy library
dot_product = 0
for a, b in zip(x, y):
    dot_product += a * b
print(dot_product) 

# using the numpy library
a = x * y
print(a.sum())

# using the dot method from the numpy library
print(x.dot(y))

32
32
32


In [19]:
# Matrix multiplication
# create two matrices
X= np.array(([1, 2, 3], [4, 5, 6]))
Y = np.array(([9, 8], [7, 5], [4, 3]))
print(X)
print(Y)
print(np.dot(X, Y))

# to multiply X and Y element-wise(both matrices must be the same shape)
arr1 = np.array(([1, 2], [3, 4]))
arr2 = np.array(([5, 6], [7, 8]))
print(np.multiply(arr1, arr2))

[[1 2 3]
 [4 5 6]]
[[9 8]
 [7 5]
 [4 3]]
[[35 27]
 [95 75]]
[[ 5 12]
 [21 32]]


In [21]:
# finding the inverse of a matrix
# finding the inverse of a 2by2 matrix
a = np.array(([1, 2], [3, 4]))
z = np.linalg.inv(a)
print(z)

# to verify if the inverse is correct we can take the dot product of a matrix with its inverse which should yield an identity matrix
identity_matrix = a.dot(z)
print(identity_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [22]:
# finding the determinant of amatrix
x = np.array(([1, 2, 3], [4, 5, 6,], [7, 8, 9]))
det = np.linalg.det(x)
det

0.0

In [23]:
# finding the trace of a matrix
x = np.array(([1, 2, 3], [4, 5, 6,], [7, 8, 9]))
trc = np.trace(x)
trc

15